export const LEGAL_LAST_UPDATED = 'January 8, 2026';

/**
 * Legal content is English-only for now (UI is translated elsewhere).
 * This file is intentionally plain JS so it can be reused by both:
 * - React UI (LegalModal)
 * - Node build scripts (static SEO pages generation)
 */

export const TERMS_SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    paragraphs: [
      'By accessing and using Banana Prompt ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.',
    ],
  },
  {
    title: '2. Description of Service',
    paragraphs: [
      'Banana Prompt is a free AI image prompt library and management tool designed to work with Nano Banana and other AI image generation platforms. The Service provides:',
    ],
    bullets: [
      'Curated AI image prompt templates',
      'Variable-based prompt customization',
      'One-click copy functionality',
      'Template sharing capabilities',
      'Local data storage for user customizations',
    ],
  },
  {
    title: '3. User Conduct',
    paragraphs: ['When using Banana Prompt, you agree not to:'],
    bullets: [
      'Use the Service for any unlawful purpose or in violation of any applicable laws',
      'Create or share prompts that generate harmful, abusive, or inappropriate content',
      'Attempt to interfere with or disrupt the Service or its infrastructure',
      'Misrepresent your identity or affiliation with any person or organization',
      'Violate the intellectual property rights of others',
    ],
  },
  {
    title: '4. Intellectual Property',
    paragraphs: [
      'The Service, including its original content, features, and functionality, is owned by Banana Prompt and is protected by international copyright, trademark, and other intellectual property laws. User-created templates and customizations remain the property of their respective creators.',
    ],
  },
  {
    title: '5. Third-Party Services',
    paragraphs: [
      "Banana Prompt is designed to work with Nano Banana and other third-party AI image generation services. Your use of these third-party services is subject to their respective terms and conditions. We are not responsible for the content generated by these platforms or their availability.",
    ],
  },
  {
    title: '6. Data Storage',
    paragraphs: [
      'All user data, including custom templates and settings, is stored locally in your browser. We do not store your data on our servers. You are responsible for backing up your data. We are not liable for any data loss resulting from browser data clearing or device issues.',
    ],
  },
  {
    title: '7. Disclaimer of Warranties',
    paragraphs: [
      'The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, secure, or error-free. Use of the Service is at your own risk.',
    ],
  },
  {
    title: '8. Limitation of Liability',
    paragraphs: [
      'In no event shall Banana Prompt, its operators, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service.',
    ],
  },
  {
    title: '9. Changes to Terms',
    paragraphs: [
      'We reserve the right to modify these Terms of Service at any time. We will notify users of any material changes by posting the new terms on the Service. Your continued use of the Service after such modifications constitutes your acceptance of the updated terms.',
    ],
  },
  {
    title: '10. Contact Information',
    paragraphs: [
      'If you have any questions about these Terms of Service, please contact us at:',
    ],
    bullets: [
      'Website: nanobananapro.site',
      'WeChat: nanobana',
      'WeChat Official Account: 面壁者逻辑说',
    ],
  },
];

export const PRIVACY_SECTIONS = [
  {
    title: '1. Introduction',
    paragraphs: [
      'Banana Prompt ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our Service.',
    ],
  },
  {
    title: '2. Information We Collect',
    paragraphs: ["We are designed with privacy in mind. Here's what you should know:"],
    bullets: [
      'Local Storage Only: All your templates, settings, and customizations are stored locally in your browser\'s IndexedDB and localStorage. This data never leaves your device.',
      'No Account Required: You can use Banana Prompt without creating an account or providing any personal information.',
      'Analytics: We use Vercel Analytics to collect anonymous usage data such as page views and basic device information to improve the Service. This data cannot identify individual users.',
    ],
  },
  {
    title: '3. How We Use Information',
    paragraphs: ['The anonymous analytics data we collect is used to:'],
    bullets: [
      'Understand how users interact with the Service',
      'Identify and fix bugs or performance issues',
      'Improve the user experience and develop new features',
      'Monitor the overall health of the Service',
    ],
  },
  {
    title: '4. Data Sharing',
    paragraphs: [
      'We do not sell, trade, or otherwise transfer your information to third parties. Since your data is stored locally on your device, we do not have access to your templates, prompts, or customizations.',
      'When you choose to share a template, the template data is temporarily processed to generate a shareable link. This data is not stored permanently on our servers.',
    ],
  },
  {
    title: '5. Third-Party Services',
    paragraphs: ['Our Service integrates with third-party services:'],
    bullets: [
      'Nano Banana: When you click "Copy and Generate", you are redirected to Nano Banana\'s platform. Their privacy policy applies to your use of their service.',
      "Vercel: We use Vercel for hosting and analytics. Vercel's privacy policy applies to the anonymous analytics data collected.",
      "GitHub: Our source code is hosted on GitHub. Their privacy policy applies if you visit our repository.",
    ],
  },
  {
    title: '6. Cookies and Local Storage',
    paragraphs: ['We use browser storage technologies to:'],
    bullets: [
      'IndexedDB: Store your templates, word banks, and large datasets locally',
      'localStorage: Store your preferences, settings, and UI state',
    ],
  },
  {
    title: '7. Data Security',
    paragraphs: ['Since your data is stored locally on your device, you are responsible for its security. We recommend:'],
    bullets: [
      'Keeping your browser and operating system updated',
      'Using the "Export All" feature to create backups of your templates',
      'Being cautious when sharing your device with others',
    ],
  },
  {
    title: "8. Children's Privacy",
    paragraphs: [
      'Our Service is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us.',
    ],
  },
  {
    title: '9. Your Rights',
    paragraphs: ['Because your data is stored locally, you have full control over it:'],
    bullets: [
      'Access: View all your data through the Service',
      'Export: Download your templates as JSON files',
      'Delete: Use "Clear All Data" to remove all stored data',
      'Portability: Export and import your data freely',
    ],
  },
  {
    title: '10. Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.',
    ],
  },
  {
    title: '11. Contact Us',
    paragraphs: ['If you have any questions about this Privacy Policy, please contact us at:'],
    bullets: [
      'Website: nanobananapro.site',
      'WeChat: nanobana',
      'WeChat Official Account: 面壁者逻辑说',
    ],
  },
];


